/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sofas: Sofa;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sofas: SofasSelect<false> | SofasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sofas".
 */
export interface Sofa {
  id: string;
  /**
   * Например: Easy, Monaco, Cloud
   */
  title: string;
  category?: string | null;
  /**
   * Название папки в public/sofas/ (например: easy, monaco). Фото берутся автоматически из этой папки.
   */
  folderName?: string | null;
  /**
   * Сколько фото в папке views/ (файлы: 1.webp, 2.webp, ...)
   */
  viewsCount?: number | null;
  imageFilename:
    | 'bad.webp'
    | 'bianco.webp'
    | 'cloud.webp'
    | 'easy.webp'
    | 'minimalist.webp'
    | 'monaco.webp'
    | 'moscow.webp'
    | 'new-york.webp'
    | 'yard.webp';
  price: number;
  oldPrice?: number | null;
  isActive?: boolean | null;
  hero?: {
    /**
     * Например: "Диван Easy"
     */
    topLine?: string | null;
    /**
     * Например: "Easy"
     */
    topBold?: string | null;
    /**
     * Например: "амбассадор комфорта в лофт стиле"
     */
    bottomLine?: string | null;
    /**
     * Например: "амбассадор"
     */
    bottomBold?: string | null;
    description?: string | null;
    /**
     * Например: "Доступен к заказу, именно для Вас"
     */
    descriptionBold?: string | null;
    bgColor?: string | null;
  };
  showcase?: {
    /**
     * Например: "Угловой диван Easy"
     */
    title?: string | null;
    description?: string | null;
  };
  info?: {
    /**
     * Например: "Оттоманка со спинкой и подлокотником, широкая сидушка..."
     */
    equipment?: string | null;
    sizes?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    materials?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Заголовок секции конфигураций. По умолчанию: "ПОПУЛЯРНЫЕ КОНФИГУРАЦИИ"
   */
  configsTitle?: string | null;
  /**
   * Подзаголовок секции конфигураций. По умолчанию: "Все параметры можно менять под себя"
   */
  configsSubtitle?: string | null;
  /**
   * Варианты конфигураций с ценами
   */
  configs?:
    | {
        title: string;
        description?: string | null;
        price: number;
        oldPrice?: number | null;
        /**
         * Например: "2000x1550x700"
         */
        dimensions?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Заголовок секции "Другие модели". По умолчанию: "Другие модели диванов"
   */
  relatedSofasTitle?: string | null;
  /**
   * Подзаголовок секции "Другие модели". По умолчанию: "Выбирайте подходящий для себя"
   */
  relatedSofasSubtitle?: string | null;
  /**
   * Выберите до 4 диванов для секции «Другие модели». Если не выбрано — покажутся первые 4 активных.
   */
  relatedSofas?: (string | Sofa)[] | null;
  /**
   * Видео для секции коротких видео
   */
  videos?:
    | {
        title: string;
        overlayText?: string | null;
        views?: number | null;
        /**
         * URL видео (например, с Supabase)
         */
        videoUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'sofas';
        value: string | Sofa;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sofas_select".
 */
export interface SofasSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  folderName?: T;
  viewsCount?: T;
  imageFilename?: T;
  price?: T;
  oldPrice?: T;
  isActive?: T;
  hero?:
    | T
    | {
        topLine?: T;
        topBold?: T;
        bottomLine?: T;
        bottomBold?: T;
        description?: T;
        descriptionBold?: T;
        bgColor?: T;
      };
  showcase?:
    | T
    | {
        title?: T;
        description?: T;
      };
  info?:
    | T
    | {
        equipment?: T;
        sizes?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        materials?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  configsTitle?: T;
  configsSubtitle?: T;
  configs?:
    | T
    | {
        title?: T;
        description?: T;
        price?: T;
        oldPrice?: T;
        dimensions?: T;
        id?: T;
      };
  relatedSofasTitle?: T;
  relatedSofasSubtitle?: T;
  relatedSofas?: T;
  videos?:
    | T
    | {
        title?: T;
        overlayText?: T;
        views?: T;
        videoUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroSection?: {
    title?: string | null;
    titleBold?: string | null;
    title2?: string | null;
    title2Bold?: string | null;
    description?: string | null;
    descriptionBold?: string | null;
    catalogButtonLabel?: string | null;
    catalogButtonSublabel?: string | null;
    showroomButtonLabel?: string | null;
    showroomButtonSublabel?: string | null;
    popularTitle?: string | null;
    popularSubtitle?: string | null;
  };
  sofasSection?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Перетаскивайте для изменения порядка отображения
     */
    selectedSofas?: (string | Sofa)[] | null;
  };
  videoSection?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * До 5 видео для главной страницы
     */
    videos?:
      | {
          title: string;
          overlayText?: string | null;
          views?: number | null;
          /**
           * URL видео (например, с Supabase)
           */
          videoUrl: string;
          id?: string | null;
        }[]
      | null;
  };
  catalogSection?: {
    title?: string | null;
    subtitle?: string | null;
    buttonLabel?: string | null;
    edition?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  header?: {
    logoDescription?: string | null;
    workingHours?: string | null;
    phone?: string | null;
    videos?: {
      /**
       * URL видео (например, с Supabase)
       */
      video1?: string | null;
      /**
       * URL видео (например, с Supabase)
       */
      video2?: string | null;
    };
    socials?: {
      telegram?: string | null;
      vk?: string | null;
      youtube?: string | null;
    };
  };
  footer?: {
    copyright?: string | null;
    privacyPolicyText?: string | null;
    privacyPolicyContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: диваны, мебель, Челябинск, производство
     */
    keywords?: string | null;
    scripts?: {
      /**
       * Только ID счетчика (например: G-1234567)
       */
      googleAnalyticsId?: string | null;
      /**
       * Только номер счетчика (например: 12345678)
       */
      yandexMetrikaId?: string | null;
      /**
       * Сюда вставляются прочие скрипты аналитики
       */
      head?: string | null;
      /**
       * Сюда вставляються коды для GTM (noscript) и др.
       */
      body?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        titleBold?: T;
        title2?: T;
        title2Bold?: T;
        description?: T;
        descriptionBold?: T;
        catalogButtonLabel?: T;
        catalogButtonSublabel?: T;
        showroomButtonLabel?: T;
        showroomButtonSublabel?: T;
        popularTitle?: T;
        popularSubtitle?: T;
      };
  sofasSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        selectedSofas?: T;
      };
  videoSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        videos?:
          | T
          | {
              title?: T;
              overlayText?: T;
              views?: T;
              videoUrl?: T;
              id?: T;
            };
      };
  catalogSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
        edition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        logoDescription?: T;
        workingHours?: T;
        phone?: T;
        videos?:
          | T
          | {
              video1?: T;
              video2?: T;
            };
        socials?:
          | T
          | {
              telegram?: T;
              vk?: T;
              youtube?: T;
            };
      };
  footer?:
    | T
    | {
        copyright?: T;
        privacyPolicyText?: T;
        privacyPolicyContent?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        scripts?:
          | T
          | {
              googleAnalyticsId?: T;
              yandexMetrikaId?: T;
              head?: T;
              body?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}